language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - pip install python-twitter
  - pip install python-rrdtool-1.4.7.tar.gz
# command to run tests
script: nosetests
